rm sse-esorics.aux
rm sse-esorics.out
rm sse-esorics.log
rm sse-esorics.bbl
rm sse-esorics.blg
pdflatex sse-esorics
bibtex sse-esorics
pdflatex sse-esorics
pdflatex sse-esorics
rm sse-esorics.aux
rm sse-esorics.out
rm sse-esorics.log
rm sse-esorics.bbl
rm sse-esorics.blg
